### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by tomxnodes**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index.js exports TVL: 
                
 
 
SAAL_main                 3.44 M
SAAL_gnb                  6.44 M
ethereum                  402.42 M
polygon                   402.42 M
avalanche                 972.66 M

total                    2.38 B

**Comment by AugustG98** [comment]
neat with the llamatester, these TVLs is just from the crv API using their URLs. will hook us up to our own API when I get the shared packages imported.

**Comment by AugustG98** [comment]
Also, readme.md now updated using the pull_request_template.md Tom pasted in above, with some of the information we do know. Not finished.

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index.js exports TVL: 
                
 
 
ethereum                  520.00 k
bsc                       520.00 k
polygon                   520.00 k
fantom                    520.00 k
andromeda                 520.00 k
avalanche                 520.00 k
treasury                  1.26 M
PFA                       1.24 M

total                    5.61 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index.js exports TVL: 
                
 
 
treasury                  1.26 M
PFA                       1.24 M
avalanche                 1.00 M
fantom                    1.00 M
bsc                       1.00 M
andromeda                 1.00 M
polygon                   1.00 M
ethereum                  1.81 M

total                    9.30 M

**Comment by AugustG98** [comment]
Any idea why I can't query networkStats > tvl on any other chainid than 1?

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index.js exports TVL: 
                
 
 
treasury                  1.26 M
PFA                       1.24 M
avalanche                 1.00 M
bsc                       1.00 M
fantom                    1.00 M
andromeda                 1.00 M
polygon                   1.00 M
ethereum                  1.82 M

total                    9.31 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index_new.js exports TVL: 
                
 
 
ethereum                  1.99 M
fantom                    96.62 k
polygon                   321.93 k

total                    2.41 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index_new.js exports TVL: 
                
 
 
fantom                    95.80 k
polygon                   324.20 k
bsc                       61.55 k
ethereum                  1.97 M
avalanche                 157.72 k

total                    2.61 M

**Comment by AugustG98** [comment]
No llamatester result after adding metis. Need to fix metis Subgraph pull. tested query from code here directly in the graphiql playground, Seems to work fine there. not sure what's wrong here.

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index_new.js exports TVL: 
                
 
 
ethereum                  1.93 M
avalanche                 153.40 k
polygon                   308.54 k
fantom                    94.17 k
bsc                       59.06 k
metis                     1.72 M

total                    4.27 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index_new.js exports TVL: 
                
 
 
bsc-staking               14.81 k
avalanche                 158.67 k
polygon                   323.96 k
fantom                    93.27 k
fantom-staking            28.36 k
polygon-staking           113.45 k
bsc                       62.82 k
ethereum                  2.02 M
avalanche-staking         31.44 k
ethereum-staking          1.25 M
andromeda                 2.15 M
andromeda-staking         352.85 k
staking                   1.79 M

total                    4.81 M

**Comment by AugustG98** [comment]
TVLs including staking (PFA tvl) is showing correctly. TODO: shine readme.md and fix offset.

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index_new.js exports TVL: 
                
 
 
avalanche-staking         30.20 k
ethereum-staking          1.20 M
ethereum                  1.92 M
polygon                   316.03 k
fantom-staking            27.24 k
fantom                    90.19 k
bsc                       61.22 k
avalanche                 152.90 k
metis-staking             338.12 k
metis                     2.01 M
polygon-staking           104.89 k
bsc-staking               14.22 k
staking                   1.72 M

total                    4.54 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index_new.js exports TVL: 
                
 
 
avalanche                 152.30 k
ethereum                  1.91 M
polygon                   315.07 k
avalanche-staking         29.79 k
fantom                    89.42 k
bsc-staking               14.03 k
fantom-staking            26.86 k
polygon-staking           104.48 k
ethereum-staking          1.19 M
metis                     1.98 M
metis-staking             333.49 k
bsc                       61.05 k
staking                   1.69 M

total                    4.50 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index_new.js exports TVL: 
                
 
 
ethereum-staking          1.19 M
avalanche-staking         29.79 k
polygon-staking           104.48 k
bsc-staking               14.03 k
ethereum                  1.91 M
avalanche                 152.30 k
polygon                   315.07 k
fantom                    89.42 k
fantom-staking            26.86 k
metis                     1.98 M
metis-staking             333.49 k
bsc                       61.05 k
staking                   1.69 M

total                    4.50 M

**Comment by 0xViva** [comment]
TODO: clean up and make fresh PR with readme.md content as a comment

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes/index.js exports TVL: 
                
 
 
ethereum                  2.03 M
bsc-staking               13.44 k
polygon                   344.41 k
avalanche                 163.84 k
fantom                    92.60 k
ethereum-staking          1.18 M
avalanche-staking         28.55 k
bsc                       64.06 k
polygon-staking           91.26 k
fantom-staking            25.74 k
metis-staking             315.45 k
metis                     2.39 M
staking                   1.65 M

total                    5.08 M

**Comment by 0xViva** [comment]
@tomxnodes If I understand you correctly here, you want me to move the config object out of index.js to make it less messy?

**Comment by 0xViva** [comment]
I think I get you now. We could move away from subgraphs using a similar structure in the commits you referenced above. But thing is, if target address is set to the farm pool, the adapter won't be able to know which positions belongs to our protocol, it will just return the entire balance of that farm back. Unless we have a similar contract that only returns our positions? @tomxnodes

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    avalanche                 151.22 k
    polygon                   343.43 k
    bsc                       61.00 k
    ethereum                  1.94 M
    fantom                    84.18 k
    avalanche-staking         24.31 k
    metis-staking             260.58 k
    ethereum-staking          966.16 k
    metis                     1.69 M
    bsc-staking               11.11 k
    fantom-staking            21.27 k
    polygon-staking           78.32 k
    staking                   1.36 M
    
    total                    4.27 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    polygon                   343.43 k
    avalanche                 151.22 k
    ethereum                  1.94 M
    fantom                    83.43 k
    bsc                       61.00 k
    avalanche-staking         24.31 k
    metis                     1.69 M
    bsc-staking               11.11 k
    metis-staking             260.58 k
    fantom-staking            21.27 k
    polygon-staking           78.32 k
    ethereum-staking          966.16 k
    staking                   1.36 M
    
    total                    4.27 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    ethereum                  1.93 M
    bsc                       60.48 k
    polygon                   331.35 k
    fantom                    82.58 k
    avalanche                 148.72 k
    ethereum-staking          907.51 k
    avalanche-staking         22.80 k
    metis                     1.45 M
    metis-staking             251.83 k
    bsc-staking               10.41 k
    fantom-staking            19.94 k
    polygon-staking           75.56 k
    staking                   1.29 M
    
    total                    4.00 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    bsc                       58.56 k
    fantom                    76.73 k
    polygon                   321.46 k
    avalanche                 144.02 k
    ethereum                  1.91 M
    avalanche-staking         23.08 k
    ethereum-staking          928.42 k
    bsc-staking               10.57 k
    metis                     1.25 M
    fantom-staking            20.65 k
    metis-staking             265.74 k
    polygon-staking           75.25 k
    staking                   1.32 M
    
    total                    3.76 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    fantom                    75.92 k
    bsc                       58.22 k
    polygon                   319.02 k
    ethereum                  1.92 M
    avalanche                 143.92 k
    ethereum-staking          934.41 k
    metis-staking             267.46 k
    avalanche-staking         23.23 k
    metis                     1.28 M
    bsc-staking               10.64 k
    fantom-staking            20.79 k
    polygon-staking           75.74 k
    staking                   1.33 M
    
    total                    3.79 M

**Comment by llamatester** [comment]
The adapter at projects/0x_nodes exports TVL: 
        
 
 
    polygon                   323.89 k
    fantom                    75.92 k
    bsc                       58.35 k
    avalanche-staking         23.38 k
    ethereum-staking          940.40 k
    ethereum                  1.94 M
    avalanche                 145.59 k
    metis                     1.29 M
    metis-staking             269.17 k
    bsc-staking               10.71 k
    fantom-staking            20.92 k
    polygon-staking           76.22 k
    staking                   1.34 M
    
    total                    3.83 M

**Pull request merged**
